server {
    listen 80;

    # Serve frontend static files directly
    location / {
        proxy_pass http://frontend:80;
    }

    # Proxy API calls to backend service
    location /api/ {
        proxy_pass http://backend:7000/;
 
    }
}
